language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

jobs:
  include:
  - stage: lint
    install: pip install -e .[lint]
    script:
    - flake8
    - mypy .
  - stage: basictest
    install: pip install -e .[tests]
    script: pytest -r a -v
  - stage: fulltest
    install: pip install -e .[tests,all]
    script: pytest -r a -v
